### ISSUE TITLE
Cannot remove non-class delegates

### ISSUE THREAD

**Issue by arthurhammer** [jonasman/MulticastDelegate#12]
Example:

```
protocol ServiceDelegate { }

class Service {
    var delegate = MulticastDelegate<ServiceDelegate>(strongReferences: true)
}

struct Struct: ServiceDelegate { }

let service = Service()
let x = Struct()

service.delegate.addDelegate(x)
service.delegate.removeDelegate(x)
// Not empty and you can't get the thing out ever again
```

Basically I'm wondering, why the generic type `T` is not restricted to classes.

**Comment by jonasman** [comment]
The generic type accepts protocols. That is why there is no restriction. In swift we cannot restrict to a protocol only.

Later i will check the bug you mention!

**Comment by arthurhammer** [comment]
Thanks for your response. I found [this comment](https://github.com/jonasman/MulticastDelegate/blob/30893396d41f8a123d3cd1a17c903a91d79e0ddf/MulticastDelegateDemoTests/MulticastDelegateDemoTests.swift#L265) in the tests. I guess using structs is indeed not indented (as I think it shouldn't be). It's unfortunate that we cannot restrict this in the API.

**Comment by jonasman** [comment]
Correct you are not supposed to add structs or enums as delegates.

**Comment by arthurhammer** [comment]
Thanks!
