### ISSUE TITLE
--

### ISSUE THREAD

**Issue by NSExceptional** [jonasman/MulticastDelegate#14]
--

**Comment by jonasman** [comment]
You are defending a guy that doesnt deserve it. Check wgat he said first...

**Comment by NSExceptional** [comment]
What did he say?

**Comment by jonasman** [comment]
Max was rude in twitter. Check his account for the reddit replies. I have a screenshot to prove if you dont find it

**Comment by NSExceptional** [comment]
Can't seem to find it but he seems to admit to being a dick himself. Hmmm

**Comment by jonasman** [comment]
He probably deleted.. well from now on he lost my respect
