### ISSUE TITLE
Add macOS Support

### ISSUE THREAD

**Issue by rudedogg** [jonasman/MulticastDelegate#15]
I've been using this library for a year or two on macOS by manually adding the source file. I'd like to use it with CocoaPods instead though (for automatic updates, etc).

If you're interested I can do a PR. I think the only requirement is adding an osx target to the .podspec. Would you also want a macOS specific demo?

Thanks for sharing this, it's worked perfectly for me!

**Comment by jonasman** [comment]
That would be great :)
Demo project is not needed.

**Comment by jonasman** [comment]
I will need to add it to pod upstream. I will do it during the weekend

**Comment by jonasman** [comment]
pod updated
