### ISSUE TITLE
CocoaPods issue: The platform of the target PROJECTNAME (iOS 11.2) is not compatible with MulticastDelegateSwift (2.1.0), which does not support ios

### ISSUE THREAD

**Issue by LinkAndreas** [jonasman/MulticastDelegate#18]
Hi João,

When updating my pods I received the following error:

**" The platform of the target `PROJECTNAME` (iOS 11.2) is not compatible with `MulticastDelegateSwift (2.1.0)`, which does not support `ios`"** 

I have attached my Podfile below:
```
platform :ios, '11.2'

target 'PROJECTNAME' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PROJECTNAME
  pod 'MulticastDelegateSwift'

end
```

I guess this is due to one of the latest commits (f601f7d3ef7f924f8a7a4c428e013f97e4509247):

```
-  s.platform = :ios, '8.0'
 -  s.platform = :osx, '10.10'
 +  s.ios.deployment_target = '8.0'
 +  s.osx.deployment_target = '10.10'
```

Do I have to change anything in my Podfile ?
Thanks a lot for maintaining the MulticastDelegate project!

Best,

Andreas

**Comment by jonasman** [comment]
I have to investigate further. Do you have cocoapods 1.4.0?

```
$ pod lib lint

 -> MulticastDelegateSwift (2.1.0)

MulticastDelegateSwift passed validation.
```

**Comment by LinkAndreas** [comment]
Hi João, thanks for your quick response.

I have cocoapods 1.4.0 installed:

`gem which cocoapods`
`/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods.rb`

when trying to update my pods with `pod update` I still get:

`The platform of the target `PROJECTNAME` (iOS 11.2) is not compatible with `MulticastDelegateSwift (2.1.0)`, which does not support `ios`.`

Best,
Andreas

**Comment by ghost** [comment]
Hi! Is happening to me exactly the same:

`[!] The platform of the target $(PROJECT_NAME) (iOS 11.0) is not compatible with MulticastDelegateSwift (2.1.0), which does not support ios.`

Thank you so much!

Alex

**Comment by jonasman** [comment]
Thanks for the report. I will have a look during the weekend.

Sent from my iPhone

On 16 Mar 2018, at 11.54, Alex Silva <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! Is happening to me exactly the same:

[!] The platform of the target Party Play (iOS 11.0) is not compatible with MulticastDelegateSwift (2.1.0), which does not support ios.

Thank you so much!

Alex

**Comment by jonasman** [comment]
for some reason pod trunk removed ios support: https://github.com/CocoaPods/Specs/blob/master/Specs/2/7/1/MulticastDelegateSwift/2.1.0/MulticastDelegateSwift.podspec.json

**Comment by jonasman** [comment]
2.1.1 now should work: https://github.com/CocoaPods/Specs/blob/master/Specs/2/7/1/MulticastDelegateSwift/2.1.1/MulticastDelegateSwift.podspec.json
