### ISSUE TITLE
Swift Package Manager support broken?

### ISSUE THREAD

**Issue by Ceylo** [jonasman/MulticastDelegate#26]
Hello,

I tried to migrate from CocoaPods to SPM in one of my projects using MulticastDelegate. I'm doing this through Xcode 11.1 using the integrated interface for a project targetting macOS.

At the final step I get this:
<img width="729" alt="Capture d’écran 2019-10-26 à 13 24 32" src="https://user-images.githubusercontent.com/451334/67618776-fb7e9000-f7f3-11e9-9c82-9d0491dde724.png">

**Comment by jonasman** [comment]
Hi! 
can you try again with on tag 2.1.5 or master branch?

**Comment by Ceylo** [comment]
Working great now, thanks!
