### ISSUE TITLE
Swift 3 branch

### ISSUE THREAD

**Issue by bubski** [jonasman/MulticastDelegate#9]
hi :)

It would be nice to maintain a Swift 3 compatible branch (i.e. compatible with the latest Xcode 8 beta).

I've got a fork [here](https://github.com/bartekchlebek/MulticastDelegate) compatible with **Xcode beta 4**.

I can make a PR to a Swift 3 branch if you make one.

**Comment by JRG-Developer** [comment]
👍  I agree it's a good idea to create a Swift 3 branch.

The branch has to exist on the repo before you can open a PR against it, right?

@jonasman Can you please create a new branch split from `master` for `swift-3` so @bartekchlebek can open a PR against it?

**Comment by jonasman** [comment]
i will create it, it is a great idea indeed. I will just wait for the other PR to be closed.

**Comment by jonasman** [comment]
There is a new branch called swift3. You can push the changes there. Or tomorrow I can do it.

**Comment by jonasman** [comment]
swift 3 branch updated with the latest xcode 8 and swift 3 code.
